### ISSUE TITLE
Running gawky fails in a fresh environment

### ISSUE THREAD

**Issue by abstractj** [abstractj/gawky#1]
./gawky aerogear                                                                                                                                    ◼
/Users/abstractj/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- term/ansicolor (LoadError)
    from /Users/abstractj/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/local/Cellar/gawky/0.0.1/gems/gawky-0.0.1/lib/gawky/status.rb:1:in `<top (required)>'
    from /Users/abstractj/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/abstractj/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/gawky/0.0.1/gems/gawky-0.0.1/lib/gawky.rb:3:in`<top (required)>'
    from /Users/abstractj/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/abstractj/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/local/Cellar/gawky/0.0.1/gems/gawky-0.0.1/bin/gawky:4:in `<top (required)>'

**Comment by abstractj** [comment]
Fixed at https://github.com/abstractj/gawky/commit/90f56cf5a57c7bb94e974ae1c153e9c82267a250
