### ISSUE TITLE
error executing gawky after install

### ISSUE THREAD

**Issue by matzew** [abstractj/gawky#7]
- cloned the repo
- issued `bundle install` on the command line
- setup of json 
- issued `gawky aerogear` on the command line

Got:

```
gawky aerogear
/Users/matzew/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:298:in `to_specs': Could not find 'gawky' (>= 0) among 30 total gem(s) (Gem::LoadError)
    from /Users/matzew/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:309:in `to_spec'
    from /Users/matzew/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /Users/matzew/.rvm/gems/ruby-1.9.3-p547/bin/gawky:22:in `<main>'
    from /Users/matzew/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
    from /Users/matzew/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by abstractj** [comment]
@matzew ahoy, the only way to run the gem cloning it is running bin/gawky. I would recommend to execute `gem install gawky --pre` which contains the latest changes.

Let me know how it goes

**Comment by matzew** [comment]
:lipstick: works great!
